export const ROUTES = {
  home: "/",
  cart: "/cart",
  login: "/login",
  users: "/users",
  store: "/store",
  orders: "/orders",
  profile: "/profile",
  reviews: "/reviews",
  register: "/register",
  checkout: "/checkout",
  wishlist: "/wishlist",
  products: "/products",
  payments: "/payments",
  adminStores: "/stores",
  dashboard: "/dashboard",
  categories: "/categories",
  productNew: "/products/new",
  becomeSeller: "/become-seller",
  categoryNew: "/categories/new",
  addresses: "/profile/addresses",
  resetPassword: "/reset-password",
  forgotPassword: "/forgot-password",
  sellerProfiles: "/seller-profiles",
  user: (id: string) => `/users/${id}`,
  checkoutSuccess: "/checkout/success",
  order: (id: string) => `/orders/${id}`,
  payment: (id: string) => `/payments/${id}`,
  category: (id: string | number) => `/categories/${id}`,
  adminStore: (id: string | number) => `/stores/manage/${id}`,
  productEdit: (id: string | number) => `/products/edit/${id}`,
  sellerProfile: (id: string | number) => `/seller-profiles/${id}`,
  productManage: (id: string | number) => `/products/manage/${id}`,
  product: (slug: string | null | undefined) => `/products/${slug ?? ""}`,
  publicStore: (slug: string | null | undefined) => `/stores/${slug ?? ""}`,
} as const;
