export const ROUTES = {
  home: "/",
  cart: "/cart",
  login: "/login",
  users: "/users",
  store: "/store",
  orders: "/orders",
  profile: "/profile",
  reviews: "/reviews",
  register: "/register",
  checkout: "/checkout",
  wishlist: "/wishlist",
  products: "/products",
  dashboard: "/dashboard",
  categories: "/categories",
  productNew: "/products/new",
  becomeSeller: "/become-seller",
  categoryNew: "/categories/new",
  addresses: "/profile/addresses",
  notifications: "/notifications",
  resetPassword: "/reset-password",
  forgotPassword: "/forgot-password",
  user: (id: string) => `/users/${id}`,
  checkoutSuccess: "/checkout/success",
  order: (id: string) => `/orders/${id}`,
  category: (id: string | number) => `/categories/${id}`,
  productEdit: (id: string | number) => `/products/edit/${id}`,
  productManage: (id: string | number) => `/products/manage/${id}`,
  product: (slug: string | null | undefined) => `/products/${slug ?? ""}`,
  publicStore: (slug: string | null | undefined) => `/stores/${slug ?? ""}`,
} as const;
