export const ROUTES = {
  home: "/",
  cart: "/cart",
  login: "/login",
  users: "/users",
  orders: "/orders",
  profile: "/profile",
  register: "/register",
  checkout: "/checkout",
  wishlist: "/wishlist",
  products: "/products",
  dashboard: "/dashboard",
  categories: "/categories",
  productNew: "/products/new",
  becomeSeller: "/become-seller",
  categoryNew: "/categories/new",
  resetPassword: "/reset-password",
  forgotPassword: "/forgot-password",
  user: (id: string) => `/users/${id}`,
  order: (id: string) => `/orders/${id}`,
  category: (id: string | number) => `/categories/${id}`,
  productEdit: (id: string | number) => `/products/edit/${id}`,
  product: (slug: string | null | undefined) => `/products/${slug ?? ""}`,
} as const;
