export const AuditAction = {
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',
  SELLER_APPROVED: 'SELLER_APPROVED',
  SELLER_REJECTED: 'SELLER_REJECTED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  SELLER_SUSPENDED: 'SELLER_SUSPENDED',
  SELLER_UNSUSPENDED: 'SELLER_UNSUSPENDED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  PAYMENT_COD_REJECTED: 'PAYMENT_COD_REJECTED',
  PAYMENT_COD_CONFIRMED: 'PAYMENT_COD_CONFIRMED',
  PAYMENT_REFUND_RECORDED: 'PAYMENT_REFUND_RECORDED',
} as const;

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];

export const AuditEntityType = {
  USER: 'User',
  ORDER: 'Order',
  PAYMENT: 'Payment',
  SELLER_PROFILE: 'SellerProfile',
} as const;
